gText_WouldYouLikeToRestYourPkmn:: @ 82726EB
    .string "Hello, and welcome to\n"
    .string "the POKéMON CENTER.\p"
    .string "We restore your tired POKéMON\n"
    .string "to full health.\p"
    .string "Would you like to rest your POKéMON?$"

gText_IllTakeYourPkmn:: @ 8272768
    .string "Okay, I'll take your POKéMON\n"
    .string "for a few seconds.$"

gText_RestoredPkmnToFullHealth:: @ 8272798
    .string "Thank you for waiting.\p"
    .string "We've restored your POKéMON\n"
    .string "to full health.$"

@ ADDED FUNCTION
gText_RestoredPkmnTookCareOfDead:: @ 8272798
    .string "It looks like one of your\n"
    .string "POKéMON died.\p"
    .string "I will put the ashes in\n"
    .string "it's POKé BALL for you.$"

gText_WeHopeToSeeYouAgain:: @ 82727DB
    .string "We hope to see you again!$"

gText_WelcomeCutShort:: @ 82727F5
    .string "Hello, and welcome to\n"
    .string "the POKéMON CENTER.\p"
    .string "We restore your tired POKéMON\n"
    .string "to full health.\p"
    .string "Would you like to…$"

@ ADDED FUNCTION
gText_NoPkmnAshesCase::
    .string "Oh no! It looks like you don't\n"
    .string "have a case to keep your\l"
    .string "POKéMON's ashes in!\p"
    .string "Here is a case that you can use.$"

@ ADDED FUNCTION
gText_ExplainAshesCase::
    .string "Oh no! It looks like you don't\n"
    .string "have a case to keep your\l"
    .string "POKéMON's ashes in!\p"
    .string "Here is a case that you can use.\p"
    .string "{PLAYER}{KUN} received Poke Ashes\n"
    .string "case!\p"
    .string "{PLAYER}{KUN} put Poke Ashes case\n"
    .string "in the KEY ITEMS pocket\p"
    .string "NURSE JOY: Anytime one of your\n"
    .string "POKéMON dies, take them to the\l"
    .string "POKéMON CENTER.\p"
    .string "A nurse JOY will respectfully\n"
    .string "incinerate your POKéMON using our\l"
    .string "CHARIZARD'S FLAMETHROWER after\l"
    .string "processing their meat and pelts for\l"
    .string "the poor.\p"
    .string "We'll then return your POKéMON in a\n"
    .string "beautiful heap of ash :)\p"
    .string "This is why we're always called\n"
    .string "nurse JOY! :)\p$"

gText_NoticesGoldCard:: @ 8272860
    .string "Th-that card…\n"
    .string "Could it be… The GOLD CARD?!\p"
    .string "Oh, the gold color is brilliant!\n"
    .string "The four stars seem to sparkle!\p"
    .string "I've seen several TRAINERS with\n"
    .string "a SILVER CARD before, but, {PLAYER},\l"
    .string "you're the first TRAINER I've ever\l"
    .string "seen with a GOLD CARD!\p"
    .string "Okay, {PLAYER}, please allow me\n"
    .string "the honor of resting your POKéMON!$"

gText_YouWantTheUsual:: @ 8272982
    .string "I'm delighted to see you, {PLAYER}!\n"
    .string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2:: @ 82729C0
    .string "Okay, I'll take your POKéMON\n"
    .string "for a few seconds.$"

gText_ThankYouForWaiting:: @ 82729F0
    .string "Thank you for waiting.$"

gText_WeHopeToSeeYouAgain2:: @ 8272A07
    .string "We hope to see you again!$"
