OldaleTown_House1_MapScripts:: @ 81FBE85
	.byte 0

OldaleTown_House1_EventScript_Woman:: @ 81FBE86
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

@ ORIGINAL TEXT
OldaleTown_House1_Text_LeftPokemonGoesOutFirst_ORIGINAL: @ 81FBE8F
	.string "When a POKéMON battle starts, the one\n"
	.string "at the left of the list goes out first.\p"
	.string "So, when you get more POKéMON in your\n"
	.string "party, try switching around the order\l"
	.string "of your POKéMON.\p"
	.string "It could give you an advantage.$"

@ MODIFIED TEXT
OldaleTown_House1_Text_LeftPokemonGoesOutFirst: @ 81FBE8F
	.string "When a POKéMON battle starts, the one\n"
	.string "at the left of the list goes out first.\p"
	.string "So, when you get more POKéMON in your\n"
	.string "party, try switching around the order\l"
	.string "of your POKéMON.\p"
	.string "It could give you an advantage.\p"
	.string "Or you can train a single POKéMON\n"
	.string "until it dies of exhaustion.\p"
	.string "It's your choice.$"